### ISSUE TITLE
Bot crashes with no exception thrown

### ISSUE THREAD

**Issue by Turbotailz** [Turbotailz/server-status-bot#1]

**Comment by Turbotailz** [comment]
This time there was an error

```
events.js:188
      throw err;
      ^

Error: Unhandled "error" event. ([object Object])
    at Client.emit (events.js:186:19)
    at WebSocketConnection.onError (/home/diversity/server-status-bot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:374:17)
    at WebSocket.onError (/home/diversity/server-status-bot/node_modules/ws/lib/event-target.js:128:16)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
    at WebSocket.finalize (/home/diversity/server-status-bot/node_modules/ws/lib/websocket.js:185:12)
    at ClientRequest._req.on (/home/diversity/server-status-bot/node_modules/ws/lib/websocket.js:635:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
```
